server:
  port: 8080

#数据库设置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.229.128:3306/test?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 123456
#-----------------------
#下面为连接池补充设置
    initialSize: 5
    # 配置获取连接等待超时的时间   
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒 
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据 
    useGlobalDataSourceStat: true
#-----------------------
#下面为redis配置
  redis:
    # Redis服务器地址
    host: 192.168.229.128
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # Redis数据库索引（默认为0）
    database: 0
    # 连接超时时间（毫秒）
    timeout: 1000
    pool:
      # 连接池中的最大空闲连接
      max-idle: 10
      # 连接池中的最小空闲连接
      min-idle: 0
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 200
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1

mybatis:
  mapper-locations: classpath:mappers/*.xml
  check-config-location: true
  type-aliases-package: org.spring.boot.po

pagehelper: 
  autoDialect: true
  closeConn: false
  reasonable: true

#showSql
logging:
  level:
    org:
      spring:
        boot:
          dao: debug

user:
  admin:
    name: hello
    role: admin
